In [12]:
import numpy as np
import time
n = 100
m = 100
q = 100
ran_max = 10
X = np.random.randint(ran_max, size=(n, m))
Y = np.random.randint(ran_max, size=(m, q))
print(X)
print()
print(Y)
print()
s = (m, q)
###
result1 = np.zeros(s)
start_time1 = time.time()
for i in range(len(X)):
   for j in range(len(Y[0])):
       for k in range(len(Y)):
           result1[i][j] += X[i][k] * Y[k][j]
finish_time1 = time.time()
print("Seconds  =", finish_time1 - start_time1)
print()
###
#If both a and b are 2-D arrays, it is matrix multiplication, but using matmul or a @ b is preferred
#If either a or b is 0-D (scalar), it is equivalent to multiply and using numpy.multiply(a, b) or a * b is preferred
###
result2 = np.zeros(s)
start_time2 = time.time()
result2 = np.matmul(X,Y)
finish_time2 = time.time()
print("Seconds  =", finish_time2 - start_time2)
print()
####
result3 = np.zeros(s)
start_time3 = time.time()
result3 = np.dot(X,Y)
finish_time3 = time.time()
print("Seconds  =", finish_time3 - start_time3)
print()
####
print("Difference  =", finish_time1 - start_time1 - finish_time3 + start_time3  )


#for r in result2:
#   print(r)
#print()
#for r in result3:
#   print(r)
#print()

[[7 0 3 ... 0 4 6]
 [2 3 8 ... 2 0 0]
 [7 2 9 ... 0 2 9]
 ...
 [9 4 1 ... 4 0 3]
 [3 6 8 ... 4 4 0]
 [3 6 4 ... 5 7 9]]

[[5 9 6 ... 8 7 2]
 [0 7 5 ... 8 5 0]
 [2 5 4 ... 6 6 5]
 ...
 [0 5 9 ... 3 2 3]
 [8 7 0 ... 8 4 3]
 [9 9 8 ... 1 1 3]]

Seconds  = 0.9972748756408691

Seconds  = 0.000997304916381836

Seconds  = 0.0

Difference  = 0.9972748756408691
